(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var k="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function l(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var m=l(this);
function n(a,b){if(b)a:{var c=m;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&k(c,a,{configurable:!0,writable:!0,value:b})}}
n("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;k(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});const p=Symbol("IS_REPEATED_FIELD");var t=Object,u=t.freeze,v=[];Array.isArray(v)&&!Object.isFrozen(v)&&(v[p]=!0);u.call(t,v);function w(a){var b;null===(b=window.AFMA_Communicator)||void 0===b?void 0:b.addEventListener("onshow",a)};/*

 SPDX-License-Identifier: Apache-2.0
*/
function x(a,b){try{const c=y(a,"custom_flags"),d=JSON.parse(c);return d?d[b]:void 0}catch(c){}}function y(a,b){a=a.getElementsByTagName("META");for(let c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content")||"";return""};var A=class{constructor(){var a=z;this.body=a;y(a,"sampling_mod");var b=y(a,"namespace");if(!b){b="ns-"+(0,Math.random)().toString(36).substr(2,5);a:{var c=a.getElementsByTagName("META");for(let d=0;d<c.length;++d)if("namespace"===c[d].getAttribute("name")&&c[d].getAttribute("index")===(0).toString()){c[d].setAttribute("content",b);break a}c=a.querySelector("#mys-meta");c||(c=document.createElement("div"),c.id="mys-meta",c.style.position="absolute",c.style.display="none",a.appendChild(c));a=document.createElement("META");
a.setAttribute("name","namespace");a.setAttribute("content",b);a.setAttribute("index",(0).toString());c.appendChild(a)}}}addEventListener(a,b){this.body.addEventListener(a,b)}};var B=class{constructor(){this.channel=4;(this.g=!(!window.mys||!window.mys.pingback))&&this.setData(43,Date.now()-window.mys.pingback.getBaseTime())}setAttribute(a,b){this.g&&window.mys.pingback.setAttribute(a,b)}setData(a,b){this.g&&window.mys.pingback.setData(a,b,this.channel)}send(a){this.g&&window.mys.pingback.send(a)}};const C=["googqscp","osdlfm"];
function D(a,b){if(!(0>a.h.indexOf(b)&&0>a.j.indexOf(b)||null==window.performance||null==window.performance.getEntries||null==window.PerformanceNavigationTiming||null==window.PerformanceResourceTiming)){var c=0<=a.h.indexOf(b)?["script"]:[],d=window.performance.getEntries(),e=0,f=0,g=0,q=0;for(let r=0;r<d.length;++r){var h=d[r];if(!(0<=h.name.indexOf("pagead2.googlesyndication.com/pagead/gen_204?id=mys")))if(h instanceof window.PerformanceNavigationTiming)e+=h.transferSize||0;else if(h instanceof
window.PerformanceResourceTiming){const H=h.initiatorType;h=h.transferSize||0;if(0==c.length||0<=c.indexOf(H))g++,f+=0==h?1:0,q+=h}}0<=a.h.indexOf(b)?(a.g.setData(16,e),a.g.setData(17,q),a.g.setData(18,g),a.g.setData(19,f)):0<=a.j.indexOf(b)&&(a.g.setData(20,q),a.g.setData(21,g),a.g.setData(22,f))}a.g.setData(b,window.performance.now());26===b&&E(a);a.g.send()}function F(a,b){a.l[b]=window.performance.now()}
function G(a,b){a.l.hasOwnProperty(b)&&(a.g.setData(b,window.performance.now()-a.l[b]),13===b&&E(a),a.g.send())}function E(a){a.g.setData(30,`${window.innerWidth}x${window.innerHeight}`);const {clientWidth:b,clientHeight:c}=a.i.body;a.g.setData(25,`${b}x${c}`)}
var J=class{constructor(){var a=I;this.g=new B;this.u=this.s.bind(this);this.o=b=>{let c="custom_error: ";b.detail&&(c+=b.detail.message);this.g.setData(2,c);this.g.send()};this.l={};this.m={["overallStart"]:()=>void D(this,3),["overallReady"]:()=>void D(this,4),["overallQuiet"]:()=>void D(this,5),["overallError"]:()=>void D(this,6),["assembleStart"]:()=>void F(this,7),["assembleReady"]:()=>void G(this,7),["decorateStart"]:()=>void F(this,8),["decorateReady"]:()=>void G(this,8),["fontStart"]:()=>
void F(this,9),["fontReady"]:()=>void G(this,9),["spanStart"]:()=>void F(this,10),["spanReady"]:()=>void G(this,10),["prepareStart"]:()=>void F(this,11),["prepareReady"]:()=>void G(this,11),["bindingStart"]:()=>void F(this,12),["bindingReady"]:()=>void G(this,12),["browserStart"]:()=>void F(this,13),["browserStartEnd"]:()=>void G(this,13),["browserReady"]:()=>void F(this,14),["browserReadyEnd"]:()=>void G(this,14),["browserQuiet"]:()=>void F(this,15),["browserQuietEnd"]:()=>void G(this,15)};this.i=
a;this.h=[23];this.j=[24]}s(a){var b=a.message||"";let c=!1;for(let d=0;d<C.length;++d){const e=C[d];if(0<=b.indexOf(e)){b=e;c=!0;break}}b=a.type+": "+b;!c&&a.lineno&&a.colno&&(b+=` at ${a.lineno}:${a.colno}`);this.g.setData(1,b);this.g.send()}};const z=document.getElementById("mys-content"),I=new A;
(function(){var a=new J;if(window.mys&&window.mys.pingback){var b=a.i.body;window.addEventListener("error",a.u);b.addEventListener("customError",a.o);window.addEventListener("click",d=>{const e=Date.now()-window.mys.pingback.getBaseTime();a.g.setData(47,`${d.clientX}x${d.clientY}@${e}`);a.g.send()},!0);if(window.performance&&window.performance.now){window.addEventListener("DOMContentLoaded",()=>void D(a,23));window.addEventListener("load",()=>void D(a,24));w(()=>void D(a,26));var c=new Map([["DOM_CONTENT_LOADED",
23],["PAGE_LOADED",24],["AFMA_ONSHOW",26],["OVERALL_READY",4],["OVERALL_QUIET",5]]);a.i.addEventListener("overallStart",()=>{const d=x(a.i.body,"check_script_loading_at"),e=x(a.i.body,"check_resource_loading_at");if(d){a.h=[];let f;for(const g of(null==(f=d)?void 0:f.split("|"))||[])a.h.push(c.get(g)||23)}if(e){a.j=[];let f;for(const g of(null==(f=e)?void 0:f.split("|"))||[])a.j.push(c.get(g)||24)}});for(const d in a.m)b.addEventListener(d,a.m[d])}}})();}).call(this);
