(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function l(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
function n(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},p;if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var r;a:{var fa={a:!0},t={};try{t.__proto__=fa;r=t.a;break a}catch(a){}r=!1}p=r?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var u=p;
function v(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(u)u(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.C=b.prototype}l("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
l("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
l("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(b,c||0)}});var ha=this||self;var w,ia="undefined"!==typeof TextEncoder;
function x(a){if(ia)a=(w||(w=new TextEncoder)).encode(a);else{var b=void 0;b=void 0===b?!1:b;for(var c=0,d=new Uint8Array(3*a.length),e=0;e<a.length;e++){var f=a.charCodeAt(e);if(128>f)d[c++]=f;else{if(2048>f)d[c++]=f>>6|192;else{if(55296<=f&&57343>=f){if(56319>=f&&e<a.length){var g=a.charCodeAt(++e);if(56320<=g&&57343>=g){f=1024*(f-55296)+g-56320+65536;d[c++]=f>>18|240;d[c++]=f>>12&63|128;d[c++]=f>>6&63|128;d[c++]=f&63|128;continue}else e--}if(b)throw Error("Found an unpaired surrogate");f=65533}d[c++]=
f>>12|224;d[c++]=f>>6&63|128}d[c++]=f&63|128}}a=d.subarray(0,c)}return a};var ja={},y=null;
function ka(a,b){void 0===b&&(b=0);if(!y){y={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));ja[e]=f;for(var g=0;g<f.length;g++){var h=f[g];void 0===y[h]&&(y[h]=g)}}}b=ja[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var m=a[f],k=a[f+1];h=a[f+2];g=b[m>>2];m=b[(m&3)<<4|k>>4];k=b[(k&15)<<2|h>>6];h=b[h&63];c[e++]=g+m+k+h}g=0;h=d;switch(a.length-f){case 2:g=
a[f+1],h=b[(g&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|g>>4]+h+d}return c.join("")};var la="function"===typeof Uint8Array.prototype.slice,ma,z=0,A=0;function B(){this.g=new Uint8Array(64);this.h=0}B.prototype.push=function(a){if(!(this.h+1<this.g.length)){var b=this.g;this.g=new Uint8Array(Math.ceil(1+2*this.g.length));this.g.set(b)}this.g[this.h++]=a};B.prototype.length=function(){return this.h};B.prototype.end=function(){var a=this.g,b=this.h;this.h=0;return 0===b?ma||(ma=new Uint8Array(0)):la?a.slice(0,b):new Uint8Array(a.subarray(0,b))};function C(a,b){for(;127<b;)a.push(b&127|128),b>>>=7;a.push(b)}
function na(a,b){if(0<=b)C(a,b);else{for(var c=0;9>c;c++)a.push(b&127|128),b>>=7;a.push(1)}}function oa(a,b){a.push(b>>>0&255);a.push(b>>>8&255);a.push(b>>>16&255);a.push(b>>>24&255)};function pa(){this.i=[];this.h=0;this.g=new B}function F(a,b){0!==b.length&&(a.i.push(b),a.h+=b.length)}function G(a){F(a,a.g.end())}function H(a,b,c){null!=c&&(C(a.g,8*b),na(a.g,c))}function qa(a,b,c){null!=c&&(c=parseInt(c,10),C(a.g,8*b),na(a.g,c))}function I(a,b,c){C(a.g,8*b+2);C(a.g,c.length);G(a);F(a,c)};var ra="function"===typeof Uint8Array;function sa(a){return null!==a&&"object"==typeof a&&!Array.isArray(a)&&!(ra&&null!=a&&a instanceof Uint8Array)}function ta(a,b){if(null!=a)return Array.isArray(a)||sa(a)?ua(a,b):b(a)}function ua(a,b){if(Array.isArray(a)){for(var c=Array(a.length),d=0;d<a.length;d++)c[d]=ta(a[d],b);Array.isArray(a)&&a.o&&J(c);return c}c={};for(d in a)c[d]=ta(a[d],b);return c}
function va(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":return ra&&null!=a&&a instanceof Uint8Array?ka(a):a;default:return a}}var wa={o:{value:!0,configurable:!0}};function J(a){Array.isArray(a)&&!Object.isFrozen(a)&&Object.defineProperties(a,wa);return a};var xa;function K(a,b,c){var d=xa;xa=null;a||(a=d);d=this.constructor.B;a||(a=d?[d]:[]);this.j=d?0:-1;this.g=null;this.h=a;a:{d=this.h.length;a=d-1;if(d&&(d=this.h[a],sa(d))){this.l=a-this.j;this.i=d;break a}void 0!==b&&-1<b?(this.l=Math.max(b,a+1-this.j),this.i=null):this.l=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.l?(a+=this.j,(d=this.h[a])?J(d):this.h[a]=L):(ya(this),(d=this.i[a])?J(d):this.i[a]=L)}var L=Object.freeze(J([]));function ya(a){var b=a.l+a.j;a.h[b]||(a.i=a.h[b]={})}
function M(a,b,c){return-1===b?null:(void 0===c?0:c)||b>=a.l?a.i?a.i[b]:void 0:a.h[b+a.j]}function N(a,b,c,d){(void 0===d?0:d)||b>=a.l?(ya(a),a.i[b]=c):a.h[b+a.j]=c;return a}function O(a,b,c,d){for(var e=0,f=0;f<c.length;f++){var g=c[f];null!=M(a,g)&&(0!==e&&N(a,e,void 0),e=g)}(c=e)&&c!==b&&null!=d&&(a.g&&c in a.g&&(a.g[c]=void 0),N(a,c,void 0));N(a,b,d)}
function P(a,b){var c=Q;a.g||(a.g={});var d=a.g[b];if(!d){var e=void 0===e?!1:e;d=M(a,b,e);null==d&&(d=L);d===L&&(d=J([]),N(a,b,d,e));e=d;d=[];for(var f=0;f<e.length;f++)d[f]=new c(e[f]);a.g[b]=d}return d}function R(a,b,c){var d=void 0===d?!1:d;if(c){var e=J([]);for(var f=0;f<c.length;f++)e[f]=S(c[f],!1);a.g||(a.g={});a.g[b]=c}else a.g&&(a.g[b]=void 0),e=L;return N(a,b,e,d)}K.prototype.toJSON=function(){var a=S(this,!1);return ua(a,va)};
function S(a,b){if(a.g)for(var c in a.g){var d=a.g[c];if(Array.isArray(d))for(var e=0;e<d.length;e++)d[e]&&S(d[e],b);else d&&S(d,b)}return a.h}K.prototype.toString=function(){return S(this,!1).toString()};function za(a,b){if(a=a.m){G(b);for(var c=0;c<a.length;c++)F(b,a[c])}};function Q(a){K.call(this,a)}v(Q,K);var T=[1,2,3],Aa=[4,5];function Ba(a){K.call(this,a,-1,Ca)}v(Ba,K);var Ca=[1];/*

 SPDX-License-Identifier: Apache-2.0
*/
function Da(a){K.call(this,a,-1,Ea)}v(Da,K);var Ea=[1,2];function U(a){this.h=a;this.data=[];this.g=[]}U.prototype.setData=function(a,b,c){this.h.includes(c)&&this.data.push({key:a,value:b,channel:c})};function Fa(a){return a.data.some(function(b){return 1===b.channel})}U.prototype.setAttribute=function(a,b){this.g.push({key:a,value:b})};function Ga(a,b,c,d){var e=new Q;"string"===typeof a?O(e,3,T,a):d?O(e,1,T,a):O(e,2,T,a);"number"===typeof b?O(e,4,Aa,b):O(e,5,Aa,b);c&&N(e,6,c);return e};function V(){this.g=new U([]);this.u=Date.now();this.h=[];this.m=this.j=!1;this.l=100}
V.prototype.init=function(a,b,c,d,e,f){var g=this;this.g=new U(b);this.A=a;this.s=e;this.v=c;if(d){b=a=NaN;d=n(d);for(c=d.next();!c.done;c=d.next())e=n(c.value),c=e.next().value,e=e.next().value,6===c?a=Number(e):5===c?b=Number(e):this.g.setAttribute(c,e);!isNaN(a)&&0<=a?this.l=a:isNaN(b)||(this.j=!0,setInterval(this.i.bind(this),b),setTimeout(function(){W(g,"timeout")},3E5),document.addEventListener("visibilitychange",function(){"hidden"===document.visibilityState&&W(g,"document_hidden")}),window.addEventListener("beforeunload",
function(){W(g,"beforeunload")}))}if(f){f=n(f);for(a=f.next();!a.done;a=f.next())d=n(a.value),a=d.next().value,b=d.next().value,d=d.next().value,this.setData(a,b,d);"complete"===document.readyState?this.send():window.addEventListener("load",function(){g.send()})}};V.prototype.getBaseTime=function(){return this.u};V.prototype.setData=function(a,b,c){this.g.setData(a,b,c);this.h[c]?this.h[c]++:this.h[c]=1};V.prototype.setAttribute=function(a,b){this.g.setAttribute(a,b)};
V.prototype.send=function(a){var b=this;if(!this.j){var c=Fa(this.g)?0:this.l;a=null!==a&&void 0!==a?a:c;0<a?setTimeout(function(){return void b.i()},a):this.i()}};
V.prototype.i=function(){if(0<this.g.data.length){var a=this.A,b=this.s,c=this.v,d=this.g,e=[];var f=n(d.g);for(var g=f.next();!g.done;g=f.next())g=g.value,e.push(Ga(g.key,g.value,void 0,!0));f=[];d=n(d.data);for(g=d.next();!g.done;g=d.next())g=g.value,f.push(Ga(g.key,g.value,g.channel,!1));d=new Da;e=R(d,1,e);f=R(e,2,f);e=new Ba;f=P(f,1).concat(P(f,2));e=R(e,1,f);a&&N(e,2,a);c&&N(e,4,c);b&&N(e,5,b);a=new pa;b=P(e,1);if(null!=b)for(c=0;c<b.length;c++){C(a.g,10);G(a);d=a.h;f=a.i.length-1;g=b[c];qa(a,
1,M(g,1));qa(a,2,M(g,2));var h=M(g,3);null!=h&&I(a,3,x(h));var m=M(g,4);if(null!=m){C(a.g,33);h=a.g;var k=m;k=(m=0>k?1:0)?-k:k;if(0===k)A=0<1/k?0:2147483648,z=0;else if(isNaN(k))A=2147483647,z=4294967295;else if(1.7976931348623157E308<k)A=(m<<31|2146435072)>>>0,z=0;else if(2.2250738585072014E-308>k){var q=k/Math.pow(2,-1074);A=(m<<31|q/4294967296)>>>0;z=q>>>0}else{var D=k;q=0;if(2<=D)for(;2<=D&&1023>q;)q++,D/=2;else for(;1>D&&-1022<q;)D*=2,q--;k*=Math.pow(2,-q);A=(m<<31|q+1023<<20|1048576*k&1048575)>>>
0;z=4503599627370496*k>>>0}oa(h,z);oa(h,A)}h=M(g,5);null!=h&&I(a,5,x(h));h=M(g,6);null!=h&&H(a,6,h);za(g,a);G(a);C(a.g,a.h+a.g.length()-d);d=a.g.end();a.h+=d.length;a.i.splice(1+f,0,d)}b=M(e,2);null!=b&&I(a,2,x(b));b=M(e,3);null!=b&&H(a,3,b);b=M(e,4);null!=b&&I(a,4,x(b));b=M(e,5);null!=b&&H(a,5,b);za(e,a);e=a.h+a.g.length();if(0===e)a=new Uint8Array(0);else{e=new Uint8Array(e);c=a.i;f=c.length;for(d=b=0;d<f;d++)g=c[d],0!==g.length&&(e.set(g,b),b+=g.length);c=a.g;f=c.h;0!==f&&(e.set(c.g.subarray(0,
f),b),c.h=0);a.i=[e];a=e}a="https://pagead2.googlesyndication.com/pagead/gen_204?id=mys&d="+ka(a,void 0).replace(/\//g,"_").replace(/\+/g,"-");e=window;if(b=e.navigator)b=e.navigator.userAgent,b=/Chrome/.test(b)&&!/Edge/.test(b)?!0:!1;if(b&&e.navigator.sendBeacon)e.navigator.sendBeacon(a);else{e.google_image_requests||(e.google_image_requests=[]);var E;b=e.document;b=void 0===b?document:b;c="IMG";"application/xhtml+xml"===(null==(E=b)?void 0:E.contentType)&&(c=c.toLowerCase());E=b.createElement(c);
E.src=a;e.google_image_requests.push(E)}this.g.data=[]}};function W(a,b){a.m||(a.g.setData(32,b,4),a.h.forEach(function(c,d){a.g.setData(31,c,d)}),a.i(),a.m=!0)}if(!window.mys||!window.mys.pingback){var Ha=new V,X=["mys","pingback"],Y=ha;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===Ha?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Ha};}).call(this);
